    COMMENT = zvault custom ports

    SUBDIR += arcsas
    SUBDIR += areca-cli
    SUBDIR += firmware
    SUBDIR += freenas-files
    SUBDIR += freenas-installer
    SUBDIR += freenas-migrate113
    SUBDIR += freenas-migrate93
    SUBDIR += freenas-webui
    SUBDIR += libhyve-remote
    SUBDIR += node9
    SUBDIR += npm5
    SUBDIR += pipewatcher
    SUBDIR += py-bsd
    SUBDIR += py-cam
    SUBDIR += py-kmip
    SUBDIR += py-midcli
    SUBDIR += py-middlewared
    SUBDIR += py-onedrivesdk
    SUBDIR += py-ws4py
    SUBDIR += py-zettarepl
    SUBDIR += samba
    SUBDIR += scanlnk
    SUBDIR += swagger-ui
    SUBDIR += tc-stats
    SUBDIR += throttle
    SUBDIR += zvio-licenselib
    SUBDIR += zvio-pkgtools
    SUBDIR += zvio-py-bsd
    SUBDIR += zvio-py-fenced

.include <bsd.port.subdir.mk>
