# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD$

PORTNAME=	throttle
PORTVERSION=	1.2
CATEGORIES=	zvault
MASTER_SITES=	http://download.freenas.org/distfiles/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A pipe bandwidth throttling utility

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
